apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplikasi-logistik
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logistik
  template:
    metadata:
      labels:
        app: logistik
    spec:
      containers:
      - name: web-server
        image: nginx:alpine
        ports:
        - containerPort: 80
