apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplikasi-logistik
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logistik
  template:
    metadata:
      labels:
        app: logistik
    spec:
      containers:
      - name: web-server
        image: asia-southeast2-docker.pkg.dev/tab-dev-playground/logistik-repo/logistik-app:v1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: aplikasi-logistik-service
spec:
  type: LoadBalancer
  selector:
    app: logistik
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
